### ISSUE TITLE
secret is not owned by kafka source?

### ISSUE THREAD

**Issue by converge** [knative-extensions/eventing-autoscaler-keda#431]
hi,

I have been trying to use eventing-autoscaler-keda, but Im unable to fix this issue after applying the kafka-source YAML. My kafka source YAML is:

```
apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: kafka-source
  namespace: my-app-namespace
  annotations:
    autoscaling.knative.dev/class: keda.autoscaling.knative.dev
    autoscaling.knative.dev/minScale: "0"
    autoscaling.knative.dev/maxScale: "5"
    keda.autoscaling.knative.dev/pollingInterval: "3"
    keda.autoscaling.knative.dev/cooldownPeriod: "10"
    keda.autoscaling.knative.dev/kafkaLagThreshold: "2"
spec:
  consumerGroup: knative-kafka-source-827e7b46-f4cc-448b-95d2-06fe303990f9
  bootstrapServers:
    - <my-bootstrap-server-here>
  topics:
    - blank-topic
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: john-test
      namespace: <my-app-namespace>
  net:
    tls:
      enable: true
    sasl:
      enable: true
      user:
        secretKeyRef:
          name: kafka-source-secret
          key: username
      password:
        secretKeyRef:
          name: kafka-source-secret
          key: password
      type:
        secretKeyRef:
          name: kafka-source-secret
          key: sasl.mechanism
```

`kubectl get kafkasource -A` shows:
```
k get kafkasource -A                
NAMESPACE                          NAME           TOPICS            BOOTSTRAPSERVERS                                   READY   REASON   AGE
<my-app-namespace>   kafka-source   ["blank-topic"]   ["<my-bootstrap-server>"]   True             3h31m
```

but the keda autoscaler controller `kubectl logs -f --selector app=eventing-autoscaler-keda-controller -n knative-eventing` shows:

```{"severity":"ERROR","timestamp":"2024-01-09T16:34:38.45483726Z","logger":"controller","caller":"controller/controller.go:566","message":"Reconcile error","commit":"7a08a0d-dirty","knative.dev/traceid":"c4ddd0c8-9d2a-4824-801e-dee9034efaba","knative.dev/key":"my-app-namespace/kafka-source","duration":"19.959125ms","error":"Secret \"kafka-source-secret\" is not owned by &{{\"\" \"\"} {\"kafka-source\"```

p.s: the kafka-source-secret secret was created manually.

Any hint what could be possibly wrong?
